moosetechnology/MooseIDE

src/Midas-Core/MiBusLogsList.class.st, src/Midas-Meta/MiModelRootBrowser.class.st, src/Midas-Tagging/MiTagDetailPage.class.st
- Migrated list presenter to filtering list on MiModelRootBrowser and changed the variable name from modelPresenter to modelFilteringList. Also deleted the accessing method modelPresenter because it was never called.
- Migrated list presenter to filtering presenter on MiBusLogsList. Changed variable name from logsList to logsFilteringList. 
- Migrated list presenter to filtering list presenter on MiTagBrowserPresenter. Also changed instance variables names to filtering list
=> Migrate from simple list to filtering list

src/Midas-Tagging/MiTagBrowser.class.st, src/Midas-Tagging/MiTagManagementPage.class.st, src/Midas-Tagging/SpRGBChooser.class.st
- I have moved the color-image-preview and the sliders into a new presenter that is called SpRGBChooser. It is located in the same Midas packages. I was thinking in modifying the spec-native presenters. But I thought that is better to create a new presenter according to our needs. Because none of the existing "rgb chooser" presenters that are already programmed in Spec do exactly what we want.
- About the bug in the slider thumb I reported it to the spec repo.
=> Color chooser on tag browser

src/Midas-Core/MiObjectInspectorPresenter.class.st
The "Breakpoints" page of the new MidasInspector were removed.
But it is still present in the Pharo inspector
=> Removed Breakpoints page from MiInspectorBrowser.

src/BaselineOfMidas/BaselineOfMidas.class.st
This PR adds the extension back in the inspectors
Maybe we will change the package and/or their name in the future.
But, at least, they will be present.
It adds navigation, moose properties, fame panel, and tree
The implementation of the tree tab will be to be fixed
=> Add the new tools extension back

src/Midas-NewTools/MooseEntity.extension.st, src/Midas-NewTools/MooseObject.extension.st
The inspector tabs were declared in `MooseObjectMoved` in the previous version (Moose Finder). (See `mooseFinderFameDescription:` and `mooseFinderNavigationIn:`).
So the fame and navigation tabs were method to `MooseObject` instead of `MooseEntity`.
=> Moving Inspector tabs definition class

src/Midas-NewTools/MiNewQueriesBrowser.class.st
In fact the redefinition of `new` method was not needed at all.
=> Removed redefinition of new method in MiNewQueriesBrowser

src/Midas-NewTools/MooseAbstractGroup.extension.st, src/Midas-NewTools/MooseEntity.extension.st, src/Midas-NewTools/MooseModel.extension.st, src/Midas-NewTools/MooseObject.extension.st
- Moose properties method declaration was moved from `MooseEntity` to `MooseObject`.
- Renamed method from `miNavigationExtension` to `miNavigationInspectorExtension`
=> Moving moose properties tab and refactors

src/Midas-NewTools/FQNumericQuery.extension.st, src/Midas-NewTools/MiNumericInlineQueryPresenter.class.st, src/Midas-NewTools/MiStringQueryInlinePresenter.class.st
New UI:
This does not affect the previous queries browser.
Also I did a little refactor: I refactored some method of string inline configuration presenter.
=> Migrate UI of query numeric configuration presenter to the new queries browser

src/Midas-NewTools/FQBooleanQuery.extension.st, src/Midas-NewTools/FQStringQuery.extension.st, src/Midas-NewTools/MiBooleanInlineQueryPresenter.class.st, src/Midas-NewTools/MiNewQueryCreationPresenter.class.st, src/Midas-NewTools/MiNumericInlineQueryPresenter.class.st, src/Midas-NewTools/MiStringInlineQueryPresenter.class.st
New UI:
This does not affect the previous queries browser:
Also, this PR does some minor refactors: 
- changes the name of the `MiStringQueryInlinePresenter` to `MiStringInlineQueryPresenter`
- adds a fixed size to the type of query dropdown list.
- refactors the layout of `MiNumericInlineQueryPresenter`
=> Migrating boolean query configuration presenter

src/Midas-FamixQueries/MiQueryCreationPresenter.class.st
In the CI log, on line 1435 (https://github.com/moosetechnology/Midas/runs/2611104812) says:
```
Testing project...
Running suite "Pharo64-9.0" with 30 tests.
....DeprecationPerformedNotification: Automatic deprecation code rewrite: The method SpPanedLayout>>#position: called from MiQueryCreationPresenter class>>#defaultSpec has been deprecated. Use #positionOfSlider: instead
SubscriptOutOfBounds: 0
```
This PR should fix this.
=> Changed SpPanedLayout>>position: to SpPanedLayout>>positionOfSlider:

.github/workflows/test.yml, src/Midas-NewTools/FQNavigationQuery.extension.st, src/Midas-NewTools/FQTypeQuery.extension.st, src/Midas-NewTools/MiMultiSelectionTable.class.st, src/Midas-NewTools/MiNavigationInlineQueryPresenter.class.st, src/Midas-NewTools/MiScopeInlineQueryPresenter.class.st, src/Midas-NewTools/MiTypeInlineQueryPresenter.class.st
Now all the configuration presenters's UI have been adapted to the new queries browser.
And now a table is opened for allowing multi-selection
This works just like the old browser. Navigation and Type queries were updated.
=> Updated the UI of the remaining configuration presenters

src/Midas-NewTools/MiInspectorBrowser.class.st
Following buses implies changing the inspector window title.
If the inspector is not open yet, window is nil.
=> Open inspector window before following buses.

.smalltalk.ston
Since we are going to remove the old queries browser we are excluding the tests of the Ci because they fails :)
We are going to add those tests to the new queries browser. So, it wont be such a problem.
=> Excluded all tests related to the old query browser

src/Midas-FamixQueries/MiQueriesCombinationPresenter.class.st, src/Midas-NewTools/FQNaryQuery.extension.st, src/Midas-NewTools/MiNAryQueryPresenter.class.st, src/Midas-NewTools/MiQueryBuilderPresenter.class.st
The name of FQNaryQuery has been changed to FQNAryQuery in the FamixQueries repo. This PR changes the reference of the old class with the new class.
=> changed name of FQNaryQuery to FQNAryQuery

src/Midas-NewTools-Tests/MiNewToolsExtenstionsTest.class.st, src/Midas-NewTools/Collection.extension.st, src/Midas-NewTools/MooseGroup.extension.st, src/Midas-NewTools/MooseModel.extension.st, src/Midas-NewTools/Object.extension.st
This method is used by UI only. It will be removed from the deprecatd package Moose-Finder in Moose.
The corresponding test is also moved.
=> Move #mooseInterestingEntity to Midas-New-Tools.

src/MooseIDE-Tests/MiAbstractBrowserTest.class.st, src/MooseIDE-Tests/MiLogBrowserTest.class.st
- Easier to read
- Less risks of timeouts
- Easier to debug
=> Split MiAbstractBrowser tests in several small tests.

src/MooseIDE-Core/MiAbstractBrowser.class.st, src/MooseIDE-Core/MiBusPresenter.class.st, src/MooseIDE-Core/MiLogBrowser.class.st, src/MooseIDE-NewTools-Tests/MiNewQueryCreationPresenterTest.class.st, src/MooseIDE-NewTools-Tests/MiQueryBuilderPresenterTest.class.st, src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
We do not need this method: browsers open on the default bus.
MiLogBrowser is the only one we may open on a specific bus. It has the method #openOnBus:
This method can be moved up to AbstractBrowser if needed later.
=> Remove #runMeFollowing:

src/MooseIDE-NewTools/MiQueryBuilderPresenter.class.st
=> now the query children go to the corresponding position

src/MooseIDE-NewTools/KMKeyCombinationChoice.extension.st, src/MooseIDE-NewTools/KMModifiedKeyCombination.extension.st, src/MooseIDE-NewTools/KMModifiedKeyCombinationSequence.class.st, src/MooseIDE-NewTools/KMShortcutPrinter.extension.st, src/MooseIDE-NewTools/MiInspectorBrowser.class.st, src/MooseIDE-NewTools/MiPlaygroundInspectInMooseCommand.class.st, src/MooseIDE-NewTools/MiPlaygroundModelsPresenter.class.st, src/MooseIDE-NewTools/MiPlaygroundPagePresenter.class.st
This includes extension of the keyboard event mapping that should not be in Moose but in pharo.
This will be proposed to pharo. In the meantime, I add it to MooseIDE so we can have our own shortcuts of the form: 
```Cmd + Shift + M + smthg```.
To open a Moose inspector from the playground, its:
```Cmd + Shift + M + I```
=> Added a MooseInspector command to the playground

src/MooseIDE-QueriesBrowser-Tests/MiQueriesBrowser.extension.st, src/MooseIDE-QueriesBrowser-Tests/MiQueriesBrowserTest.class.st, src/MooseIDE-QueriesBrowser-Tests/MiQueriesListPresenterTest.class.st, src/MooseIDE-QueriesBrowser-Tests/MiQueryListItemPresenter.extension.st, src/MooseIDE-QueriesBrowser-Tests/MiQueryListItemPresenterTest.class.st, src/MooseIDE-QueriesBrowser/FQAbstractQuery.extension.st, src/MooseIDE-QueriesBrowser/FQNAryQuery.extension.st, src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st, src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st, src/MooseIDE-QueriesBrowser/Object.extension.st
Fixed: when you create a query that is a child of a nary or complement query it does not have the correct indentation
=> Fixed when you create a query that is a child nary or complement query it does not have the correct indentation

src/MooseIDE-Famix/MiSourceTextBrowser.class.st, src/MooseIDE-Famix/MiSourceTextBrowserModel.class.st
first step of a possibly long journey:
- Moved some behavior from MiSourceTextBrowser to its model
- when there is no source code to display, the error message is in red
=> MiSourceTextBrowser highlighting

src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st
Fix #362 : Reset subscribtions to QueriesListChangedAnnouncement when removing queries.
=> Fix #362 clear queries in QueryBrowser

src/MooseIDE-NewTools/MiModelNavigationBrowser.class.st, src/MooseIDE-NewTools/MooseModel.extension.st, src/MooseIDE-NewTools/MooseObject.extension.st
This PR aims to fix a problem with the Navigation panel when inspecting a MooseModel that does not show all the possible entities.
It may duplicate the navigation entries when we have a FamixModel with classes, methods, *etc.* but it also allows us to use model with other kind of entities (for custom model such as Casino)
fix #407
fix #582
=> Fix Moose Inspector navigation pane when inspecting a MooseModel

src/MooseIDE-Famix/MiSourceTextBrowserModel.class.st
=> SourceCodeBrowser now resets highlights when receiving new entities

src/MooseIDE-Duplication/MiDuplicationBrowserModel.class.st, src/MooseIDE-Tests/MiDuplicationBrowserModelTest.class.st, src/MooseIDE-Tests/MiDuplicationBrowserTest.class.st
=> 655 clicking on a method name in the duplication browser causes exception

src/MooseIDE-Export/MiExportBrowser.class.st
Changed evaluated name to display the name shown in an inspector for every entity, including associations.
Before the changes, an association's name was displayed as "noname", so the exporter was useless for those entities.
Using displayStringOn: fixes the problem. 
The test MooseObjectTest>>testAllMooseDisplayOn also seems to suggest that this change would work on every entity.
=> MiExportBrowser: evaluating name using displayStringOn:

src/Famix-CriticBrowser-Entities/FamixCBRootContext.class.st, src/MooseIDE-CriticBrowser/MiCriticBrowser.class.st, src/MooseIDE-CriticBrowser/MiCriticBrowserModel.class.st
In my opinion, the critics browser should accept any kind of Moose Entity and not only the users of FamixTNamedEntity.
Or we cannot use it with Fast, Casino, and other kinds of metamodel that can appear (SQL, and so on).
I have updated FamixCBRootContext  to use mooseName instead of name (mooseName is the correct keyword to retrieve name of entities)
and the MiCriticBrowserModel setEntities to accept every kind of entity.
Maybe we can change it to something like allSatisfy: isMooseEntity?
Also, I have fixed a strange bug with collection
=> The critics browser should accept every kind of moose entity

src/MooseIDE-Export/MiExportModel.class.st, src/MooseIDE-Tests/MiExportModelTest.class.st
Add the return statement and a test to ensure keeping this feature in the future
=> [ExportBrowser] addQueryColumn should retrun the newly created column

src/Famix-CriticBrowser-Entities/FamixCBModel.class.st
The metamodel has been updated in https://github.com/moosetechnology/Famix/pull/507
This PR aims to regenerate the MooseIDE metamodels (only one is concerned) to follow Famix's improvement and restore Moose image building
=> Update FamixCriticsBrowser to last version

src/MooseIDE-Core/MiModelUtilityCommand.class.st, src/MooseIDE-Meta/MiModelRootBrowser.class.st, src/MooseIDE-Meta/MiModelRootBrowserModel.class.st
Implemented my own solution to fix 711
LABSARI solution in another PR was not very good (recreating a new model each time we need one (like right click on the model to get a contextual menu)
=> 711 models browser utilities are disabled when stubs are filtered out

src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserTest.class.st, src/MooseIDE-CriticBrowser/MiCriticBrowserModel.class.st
This PR reduces the number of collection copy to optimize the Critic browser
=> CriticBrowser optimization - reduce number of collection copy in model code

src/MooseIDE-NewTools/MiInspectorBrowser.class.st
`asCollection` is calling `asOrderedCollection` which is the deprecated method. To fix this issue, we applied changes with @uNouss only for the main method, to avoid changing `asCollection` that is called in many many methods.  The changes are applied as recommended by the deprecation comments of `asOrderedCollection` method: `(OrderedCollection with: @receiver)`
=> Fixing 914

src/MooseIDE-Core/MiAbstractBrowser.class.st
Because in Pharo 12 classes without comment return nil
=> Ensure #helpMessage can work when there is no comment on a browser

src/MooseIDE-CoUsageMap/MiCoUsageMapModel.class.st, src/MooseIDE-Meta/MiImportModelFromSmalltalkDialog.class.st
In Pharo 12 the way to access the package organizer changed. I added the new way to PharoBackwardCompatibility so that we can use the new way in any Moose image. This change is to use it
=> Update package organizer API

src/MooseIDE-Core/MiAbstractBrowser.class.st, src/MooseIDE-Core/MiModelUtilityCommand.class.st, src/MooseIDE-Core/MiPropagateCommand.class.st, src/MooseIDE-Meta/MiModelsBrowser.class.st, src/MooseIDE-Meta/MiModelsBrowserModel.class.st, src/MooseIDE-NewTools/MiModelsBrowser.extension.st, src/MooseIDE-Tests/MiModelsBrowserTest.class.st
The model browser can be really slow if we have big models in the image. This is due to the fact that propagating is filtering the stubs. But this means that #canPropagate it always filtering the stubs without using any cache (it would be hard to cache this). 
I propose to not filter in #canPropagate because we should almost never have a model without non stub entities and this will make the tools way smoother. We'll filter only on the propagate.
Fixes #976
=> Speed up Models browser

src/MooseIDE-Tagging/MiTagManagementPage.class.st
This is a first step at speeding up the tag browser. We were refreshing twice the description page of the tag browser making it really slow. Now I propose to refresh it only once.
With an image of 1.7Go this makes the opening time go from 21sec to 9sec.
=> Make tag browser twice faster

src/MooseIDE-Tagging/MiTagBrowser.class.st, src/MooseIDE-Tagging/MiTagExtentPage.class.st, src/MooseIDE-Tagging/MiTagManagementPage.class.st
Do not sort untagged entities if there are more than 10000
Fixes #979
=> Speed up opening of tag browser on big models

src/MooseIDE-Core/MiAbstractVisualizationBrowser.class.st, src/MooseIDE-Famix/MiUMLBrowser.class.st, src/MooseIDE-NewTools/MiAbstractBrowser.extension.st, src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st, src/MooseIDE-Tests/MiUMLBrowserTest.class.st, src/MooseIDE-Visualization/MiAbstractVisualization.class.st
Some browsers and calling #mooseInterestingEntity in their #miSelectedItem method. This will either return a moose entity if a collection has 1 element or return a moose specialized group.
I think this is not a good idea because this means we will generate moose groups each time we ask for the selected entity, which can happen often. For exemple to know if we should display the propagate or the inspect button in each browsers, at each refresh. 
In an image with small models this can be ignored, but when you start to have big models it becomes really long to always create moose groups of thousands of elements. 
I propose to remove the call to this method and instead to use it only in one place: The MiInspect command. This is, I think, the only place where it is interesting to have a …
=> Speed up a few browsers

src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowser.class.st, src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st, src/MooseIDE-Dependency/MiDependencyStructuralMatrixVisualization.class.st, src/MooseIDE-Dependency/MiDistributionMapBrowser.class.st, src/MooseIDE-Dependency/MiDistributionMapBuilder.class.st, src/MooseIDE-Dependency/MiDistributionMapInspectNodeMenuItem.class.st, src/MooseIDE-Dependency/MiDistributionMapMenuItem.class.st, src/MooseIDE-Dependency/MiDistributionMapModel.class.st, src/MooseIDE-Dependency/MiDistributionMapNodeMenuItem.class.st, src/MooseIDE-Dependency/MiDistributionMapVisualization.class.st, src/MooseIDE-Dependency/MiHDistributionMapStyle.class.st, src/MooseIDE-Dependency/MiRSDependencyStructuralMatrix.class.st, src/MooseIDE-Tests/MiDependencyStructuralMatrixBrowserTest.class.st, src/MooseIDE-Tests/MiDistributionMapBrowserTest.class.st
I tried to find some classes about disctribution maps but that was hard because the names of those classes have "DM" in the name instead of "DistributionMap".
This is the same for DependencyStructuralMatrix. 
I propose to remove the abbreviations from the names to make it more explicit.
=> Rename classes with abbreviations in the names

src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st, src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st, src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
This change speeds up once again the Architectural map and the other visu using the hierarchical. 
- Use a simple OrderedCollections instead of a MooseGroup
- Depend on the main branch of HierarchicalVisualizations project that got some improvements
- Use the new #rawRunOnEntity: that is more efficient
=> New Architectural Map and other visualizations speed ups

src/MooseIDE-Core/MiButtonEditablelistSettingItem.class.st, src/MooseIDE-Core/MiButtonListSettingItem.class.st, src/MooseIDE-Dependency/MiDistributionMapModel.class.st
Moving `display:` and `displayIcon:` to `MiButtonListSettingItem` wich is the superclass of `MiButtonEditablelistSettingItem` and `MiButtonSelectableListSettingItem`
=> [FIX}: Replacing button with editable list setting by button with selectable list setting

src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
buildNodeFromEntity: is returning nils but createRootNodes was not taking them into account. Now it does.
Fixes #999
=> Fix architectural map

src/MooseIDE-NewTools/MiNavigationBrowser.class.st
Instead of sorting by default, add sorting arrows in the column header.
=> Change sorting mechanisme in Navigation inspector pane for Moose groups

src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st, src/MooseIDE-Dependency/MiArchitecturalMapStyle.class.st, src/MooseIDE-Dependency/MiDistributionMapBuilder.class.st
The styles are not storing any state specific to a node so we can create one style for a whole architectural visualization and save hundreds of thousands of instances of styles.
=> Architectural: Do not create one style by node

src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st, src/MooseIDE-Dependency/MiArchitecturalMapStyle.class.st
This change allows one to open/collapse nodes with a double click instead of going in the menus. This also speed up the opening of the nodes that is pretty slow on big models.
Fixes #1018
=> Architectural: Open nodes on double click + speed up

src/MooseIDE-Dependency/MiArchitecturalMapStyle.class.st
Currently in the architectural visualization if an entity contains multiple time the same tag it'll have a multi tag icon instead of an icon for the specific tag.
This fixes it.
=> Architectural: Do not show multi tags if all tags are the same

src/MooseIDE-Dependency/MiArchitecturalMapBrowser.class.st
MiArchitecturalMapBrowser>>open currently returns MiArchitecturalMapBrowser class but it should return the opened instance.
This is to help me script the manipulation of browsers for Moose security
=> MiArchitecturalMapBrowser>>open should return the instance

src/MooseIDE-QueriesBrowser/FQAbstractQuery.extension.st, src/MooseIDE-QueriesBrowser/FQBooleanQuery.extension.st, src/MooseIDE-QueriesBrowser/FQComplementQuery.extension.st, src/MooseIDE-QueriesBrowser/FQIntersectionQuery.extension.st, src/MooseIDE-QueriesBrowser/FQNAryQuery.extension.st, src/MooseIDE-QueriesBrowser/FQNavigationQuery.extension.st, src/MooseIDE-QueriesBrowser/FQNullQuery.extension.st, src/MooseIDE-QueriesBrowser/FQNumericQuery.extension.st, src/MooseIDE-QueriesBrowser/FQRelationQuery.extension.st, src/MooseIDE-QueriesBrowser/FQResultSizeQuery.extension.st, src/MooseIDE-QueriesBrowser/FQRootQuery.extension.st, src/MooseIDE-QueriesBrowser/FQScopeQuery.extension.st, src/MooseIDE-QueriesBrowser/FQScriptQuery.extension.st, src/MooseIDE-QueriesBrowser/FQStringQuery.extension.st, src/MooseIDE-QueriesBrowser/FQSubtractionQuery.extension.st, src/MooseIDE-QueriesBrowser/FQTaggedEntityQuery.extension.st, src/MooseIDE-QueriesBrowser/FQTypeQuery.extension.st, src/MooseIDE-QueriesBrowser/FQUnaryQuery.extension.st, src/MooseIDE-QueriesBrowser/FQUnionQuery.extension.st, src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
Fix #1005.
Queries are now sorted by their arity before being sorted alphabetically. I would have loved to add separators in the droplist but Spec did not want me to.
=> Sort queries a bit smarter.

src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st, src/MooseIDE-Spotter-Tests/StMooseProcessorTest.class.st, src/MooseIDE-Spotter-Tests/package.st, src/MooseIDE-Spotter/FamixTSourceEntity.extension.st, src/MooseIDE-Spotter/StMooseEntry.class.st, src/MooseIDE-Spotter/StMooseProcessor.class.st, src/MooseIDE-Spotter/package.st
With this PR, it is possible to searcg using the spotter some Moose entities.
(I added the basic infrastructure here, it can be improved a lot to display additional information)
When you perform a search, it automatically search through the first moose model. 
If there is a lot of data, search in the spotter for the "#Moose" category.
This idea comes from the old moosebook in which the feature was implemented.
=> Search Moose entities using the spotter

src/MooseIDE-Core/MooseObject.extension.st, src/MooseIDE-Tests/HMiPropagateMenuItemTest.class.st, src/MooseIDE-Visualization/HMiPropagateMenuItem.class.st
I also wanted to add a test but there's too much stuff to setup and I got fed up, so here's what I got so far:
```st
testPropagateToSelectedBuses
| bus browser receivingBrowser root node visualization shape propagate model |
bus := MiBus named: 'TestBus'.
browser := MiSystemComplexityBrowser new followBus: bus.
receivingBrowser := MiClassBlueprintBrowser new followBus: bus.
model := FamixStClass named: 'AClass'.
root := HNode new name: 'Visualization'.
node := HNode new
name: 'aNode';
rawModel: model.
root add: node.
visualization := HSimpleVisualizationBuilder new
rootNode: root;
build.
browser	runVisualization.
propagate := HMiPropagateMenuItem new
shape: (visualization canvas shapeFromModel: node);
visualization: visualization.
"Trigger the propagate menu item."
propagate target …
```
=> Fix #1070: Propagate from popup menu respects chosen buses

src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st, src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
Add menu for architectural map to choose the action on double click.
=> Fix # 1018

src/MooseIDE-Core/MiAbstractBrowser.class.st
There was an empty first line, and the methods made lots of copies... Now, no empty line and no copies.
=> Fix `MiAbstractBrowser >> #helpMessage`

src/MooseIDE-CriticBrowser/MiCBEditContextPresenter.class.st, src/MooseIDE-CriticBrowser/MiCBEditRulePresenter.class.st
- Update MiCBEditContextPresenter >> initializePresenters  and  MiCBditRulePresenter >> initializePresenters to have "Confirm" button instead of "Edit rule" and "Edit context"
- Fix #1116
=> Change the names of the buttons in Critic Browser for Context and Rule

src/MooseIDE-Export/MiExportBrowser.class.st
by first computing the set of the mooseDescriptions of the entities in the group as parameter. And then by computing the primitiveProperties for only this set.
Fix #1136
=> Optimize the way to compute commonProperties 

src/MooseIDE-Dependency/FamixTClass.extension.st, src/MooseIDE-Dependency/FamixTMethod.extension.st, src/MooseIDE-Dependency/FamixTPackage.extension.st, src/MooseIDE-Dependency/FamixTTypedEntity.extension.st, src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st, src/MooseIDE-Dependency/TEntityMetaLevelDependency.extension.st
Add methods to handle declared type dependencies.
=> Fixed #1191

src/MooseIDE-Famix/MiExternalEditorOpenner.class.st, src/MooseIDE-Famix/MiSourceTextExternalEditorIntellij.class.st
=> 1243 source code browser opening external editor on windows

src/MooseIDE-Core/MooseLoadFamixSQLMenuCommand.class.st
With @alesshosry 
Currently trying to load FamixSQL (https://github.com/moosetechnology/FamixSQL) will result in an error due to the refactoring of `WeakRegistry` class in a dependency (https://github.com/pharo-rdbms/Pharo-ODBC)
This can be bypassed by replacing the reference to `WeakRegistry` by `FinalizationRegistry` when loading it. 
There are two references to `WeakRegistry` in Pharo-ODBC:
- `ODBCConnection class>>#newConnections` that can be fixed at loading time and  
- `ODBCConnection>>#initializeStatements` that can be fixed after.
A pull request has been opened in Pharo-ODBC to fix it for the latest versions of Pharo and Moose (https://github.com/pharo-rdbms/Pharo-ODBC/pull/11). Once accepted, this feature should work and fix #1193
=> Add a library menu item to load Famix SQL - Not working yet

src/MooseIDE-Dependency/MiDeadCodeJavaImplementedInterfaceHeuristic.class.st
Because we might want to move out of CollectionExtensions as a dependency of Famix
=> Use #detect:ifFound: instead of #detect:ifOne:

src/MooseIDE-Core/MiAbstractBrowser.class.st, src/MooseIDE-Core/MooseRegenerateAllConcreteMetamodelsMenuCommand.class.st, src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
QueriesBrowser use TEntityMetaLevelDependency instead of TNamedEntity to filter entities
=> QueriesBrowser : use TEntityMetaLevelDependency

src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
We cannot stay on an old tag forever.
Roassal has some issues that have been fixed in P13, namely the inspector tabs, and things like this will continue to happen.
We need to use the Pharo version.
=> Remove Roassal from the baseline
