moosetechnology/MooseIDE

- src/Midas-Dependency/MiTreeBrowser.class.st
- src/Midas-Dependency/MiTreeMapVisualisationBrowser.class.st
- src/Midas-Dependency/MiTreeVisualisationBrowser.class.st
- src/Midas-Famix/MiFilesBrowser.class.st
- src/Midas-Famix/MiNonUsedMethodBrowser.class.st
- src/Midas-Famix/MiSourceTextBrowser.class.st
- src/Midas-Famix/MiUMLBrowser.class.st
- src/Midas/AbstractBrowserMode.class.st
- src/Midas/BrowserModeFollow.class.st
- src/Midas/BrowserModeFreeze.class.st
- src/Midas/BrowserModeHighlight.class.st
- src/Midas/MiAbstractBrowser.class.st
- src/Midas/MiFameBrowser.class.st
- src/Midas/MiModelRootBrowser.class.st
- src/Midas/MiMooseModelBrowser.class.st
- src/Midas/MiPanel.class.st
- src/Midas/MiPropertyBrowser.class.st
Change  the browser mode logic
fix #3
> 3-Improve-browser-strategy

- src/Midas-Core/AbstractBrowserMode.class.st
- src/Midas-Core/MiAbstractBrowser.class.st
- src/Midas-Core/MiLogBrowser.class.st
- src/Midas-Core/MiLogger.class.st
- src/Midas-Core/MiLoggerBrowser.class.st
- src/Midas-Core/MiSelectedEntityLog.class.st
- src/Midas-Core/MidasIcons.class.st
- src/Midas-Famix/MiFilesBrowser.class.st
A bit of cleaning + a small Logger browser
No tests :-(
> Some small stuff

- src/Midas-Core/MiLogBrowser.class.st
- src/Midas-Dependency/MiDependencyBrowser.class.st
- src/Midas-Dependency/MiTreeBrowser.class.st
- src/Midas-Dependency/MiTreeMapVisualisationBrowser.class.st
- src/Midas-Dependency/MiTreeVisualisationBrowser.class.st
- src/Midas-Famix/MiFilesBrowser.class.st
- src/Midas-Famix/MiNonUsedMethodBrowser.class.st
- src/Midas-Famix/MiSourceTextBrowser.class.st
- src/Midas-Famix/MiUMLBrowser.class.st
- src/Midas-FamixQueries/MiQueriesBrowser.class.st
- src/Midas-Meta/MiFameBrowser.class.st
- src/Midas-Meta/MiModelRootBrowser.class.st
- src/Midas-Meta/MiMooseModelBrowser.class.st
- src/Midas-Meta/MiPropertyBrowser.class.st
remove browser at the end of the title
fix #40
> 40-Remove-Browser-from-the-name-of-all-browsers

- src/Midas-FamixQueries/MiQueryCreationPresenter.class.st
- src/Midas-FamixQueries/MiResultTreePresenter.class.st
- src/Midas-FamixQueries/MiScopeQueryPresenter.class.st
- src/Midas-FamixQueries/MiTypeQueryPresenter.class.st
- src/Midas-Meta/MiMooseModelBrowser.class.st
Speed up multiple presenters of Midas
> speed-up-browsers

- src/Midas-Core/MiAbstractBrowser.class.st
- src/Midas-Core/MiOverviewBrowser.class.st
- src/Midas-Dependency/MiAbstractDependencyBrowser.class.st
- src/Midas-Famix/MiAbstractFamixBrowser.class.st
- src/Midas-Famix/MiFilesBrowser.class.st
- src/Midas-Famix/MiNonUsedMethodBrowser.class.st
- src/Midas-Famix/MiSourceTextBrowser.class.st
- src/Midas-Famix/MiUMLBrowser.class.st
- src/Midas-Meta/MiFameBrowser.class.st
- src/Midas-Meta/MiModelRootBrowser.class.st
- src/Midas-Meta/MiMooseModelBrowser.class.st
- src/Midas-Meta/MiPropertyBrowser.class.st
- src/Midas-Telescope/MiAbstractTelescopeBrowser.class.st
- src/Midas-Telescope/MiCycleDependenciesBrowser.class.st
- src/Midas-Telescope/MiDependencyButterflyBrowser.class.st
- src/Midas-Telescope/MiDistributionMapBrowser.class.st
- src/Midas-Telescope/MiNavigationTreeBrowser.class.st
Starting to revamp moose menu towards end-user instead of implementer point of view
> Revamping Moose menu

- src/Midas-Core/MiBusesPopup.class.st
It should fix #80.
Things done:
- Deleted the "Accept" button.
- Added Meta + S key bindings for accepting the text in the text input.
- Modified Layout.
- Deleted dismiss method because the only caller was the accept button that was deleted.
> Small refactors on MiBusesPopup

- src/Midas-Core/MiInspectorBrowser.class.st
Fixes #116 
Added the moose inspector to the moose menu.
I do not know if is in the correct position though.
> Added inspector to the moose menu

- src/Midas-Core/MiAbstractBrowser.class.st
- src/Midas-Core/MiLogBrowser.class.st
- src/Midas-Export/MiExportBrowser.class.st
- src/Midas-NewTools/MiInspectorBrowser.class.st
- src/Midas-NewTools/MiNewQueriesBrowser.class.st
Separated the new tools into a new section and added icons.
We can change or remove the icons later if they do not fit.
> Reorganizing Midas World Menu

- src/Midas-NewTools/MiInspectorBrowser.class.st
Added action to update the Inspector's window title when receiving an entity from the bus.
> Update Inspector window title when receiving an entity from the bus

- src/BaselineOfMidas/BaselineOfMidas.class.st
- src/Midas-NewTools-Tests/MiInspectorBrowser.extension.st
- src/Midas-NewTools-Tests/MiInspectorBrowserTest.class.st
- src/Midas-NewTools-Tests/MiNewQueriesBrowser.extension.st
- src/Midas-NewTools-Tests/MiNewQueriesBrowserTest.class.st
- src/Midas-NewTools-Tests/MiQueryBuilderPresenter.extension.st
- src/Midas-NewTools-Tests/MiQueryBuilderPresenterTest.class.st
- src/Midas-NewTools-Tests/MiQueryCodePresenter.extension.st
- src/Midas-NewTools-Tests/package.st
- src/Midas-NewTools/MiNewQueriesBrowser.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
- src/Midas-NewTools/MiQueryBuilderPresenter.class.st
> #140 inspector and new queries browser does not have tests

- src/BaselineOfMidas/BaselineOfMidas.class.st
This PR tries to fix the CI broken since https://github.com/moosetechnology/Midas/commit/db5ba1e931a4dc03d2c088769fd09760d2eef729
> I don't know how one can break the CI by using the PR with security checks. We have to verify that
> Fix baseline with NewTools-Tests

- src/Midas-FamixQueries/MiQueryConfigurationPresenter.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
The methods added and disable were added to the configuration presenter. 
This is for enabling or disabling the specific presenters of the configuration presenter.
> Add disable and enable for configuration queries

- src/Midas-FamixQueries/MiQueryConfigurationPresenter.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
Reverts moosetechnology/Midas#146 because the tests for the queries browser fails.
> Revert "Add disable and enable for configuration queries"

- src/Midas-FamixQueries/MiQueryConfigurationPresenter.class.st
- src/Midas-NewTools-Tests/MiQueryBuilderPresenterTest.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
Adds disable and enable functionality to the configuration presenters.
> Add disable to inline configuration presenters

- src/Midas-Core/MiPresenter.class.st
- src/Midas-FamixQueries/MiBooleanQueryPresenter.class.st
- src/Midas-NewTools-Tests/MiNewQueryCreationPresenter.extension.st
- src/Midas-NewTools-Tests/MiNewQueryCreationPresenterTest.class.st
- src/Midas-NewTools/MiBooleanInlineQueryPresenter.class.st
- src/Midas-NewTools/MiNewQueriesBrowser.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
- src/Midas-NewTools/MiQueryBuilderPresenter.class.st
> Sprint issue 157

- src/Midas-NewTools/FamixStAccess.extension.st
- src/Midas-NewTools/MiAbstractGroupNavigationBrowser.class.st
- src/Midas-NewTools/MiModelNavigationBrowser.class.st
- src/Midas-NewTools/MiNavigationBrowser.class.st
- src/Midas-NewTools/MooseObject.extension.st
- src/Midas-NewTools/Object.extension.st
- src/Midas-NewTools/Pragma.extension.st
> 133 navigation tab of the moose inspector is not displaying names correctly

- src/Midas-NewTools/MiInspectorBrowser.class.st
> added ifNil conditional to ensure not to call the window of the presenter when is nil

- src/Midas-Dependency/MiTreeBrowser.class.st
> Now MiTreeBrowser handles propagation

- src/Midas-Dependency/TEntityMetaLevelDependency.extension.st
> The tree inside the Midas Inspector should not be a Midas browser

- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
- src/Midas-NewTools/MiNumericInlineQueryPresenter.class.st
This along side a change in FamixQueries fixes #170
> Notified when query changed when negated

- src/Midas-NewTools/MiNewQueriesBrowser.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
- src/Midas-NewTools/MiQueryBuilderPresenter.class.st
Add a number label on each of the queries in the new queries browser.
> Add a number label on each of the queries in the new queries browser

- src/Midas-FamixQueries-Tests/MiQueriesCombinationPresenterTest.class.st
- src/Midas-FamixQueries/FQSubtractionQuery.extension.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
Because it was an orthographic error.
> Renamed FQSubstractionQuery to FQSubtractionQuery

- src/Midas-Tagging/SpRGBChooser.class.st
> Changed reference from SpSliderInput to SpSliderInputPresenter

- src/Midas-Tagging/MiTagBrowser.class.st
- src/Midas-Tagging/MiTagManagementPage.class.st
- src/Midas-Tagging/SpRGBChooser.class.st
- src/Midas-Tests/SpRGBChooserTest.class.st
> Color sample in tag browser

- src/Midas-FamixQueries/MiPropertyQueryPresenter.class.st
- src/Midas-FamixQueries/MiTypeQueryPresenter.class.st
- src/Midas-NewTools/FQComplementQuery.extension.st
- src/Midas-NewTools/MiNegationQueryPresenter.class.st
- src/Midas-NewTools/MiNewQueriesBrowser.class.st
- src/Midas-NewTools/MiNewQueryCreationPresenter.class.st
- src/Midas-NewTools/MiQueryBuilderPresenter.class.st
Adding negation query configuration presenter. Removed all negation operations from the other queries. The only way to do a negation now is with the new complement (negation) query.
> Adding negation query presenter

- src/Midas-NewTools/FQIntersectionQuery.extension.st
- src/Midas-NewTools/FQNaryQuery.extension.st
- src/Midas-NewTools/FQSubtractionQuery.extension.st
- src/Midas-NewTools/FQUnionQuery.extension.st
- src/Midas-NewTools/MiAndQueryPresenter.class.st
- src/Midas-NewTools/MiDifferenceQueryPresenter.class.st
- src/Midas-NewTools/MiNAryQueryPresenter.class.st
- src/Midas-NewTools/MiOrQueryPresenter.class.st
After modifying FamixQueries repo, the functionality for doing the n-ary operations on the new queries browser has been added.
> Added the functionality on the queries browser to do the n-ary operations

- .smalltalk.ston
- src/BaselineOfMidas/BaselineOfMidas.class.st
- src/Midas-FamixQueries-Tests/MiResultTreePresenter.extension.st
- src/Midas-FamixQueries/MiResultTreePresenter.class.st
It will not be loaded, neither will be the associated tests.
> Remove old Midas-Famix package from baseline.

- src/MooseIDE-NewTools/MiNAryQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNegationQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNewQueryCreationPresenter.class.st
- src/MooseIDE-NewTools/MiQueryBuilderPresenter.class.st
- src/MooseIDE-NewTools/MiQueryConfigurationPresenter.class.st
> recompute n-ary drop list of queries

- src/MooseIDE-NewTools/MiBooleanQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNAryQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNavigationQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNegationQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNewQueryCreationPresenter.class.st
- src/MooseIDE-NewTools/MiNoPossibleQueryPresenter.class.st
- src/MooseIDE-NewTools/MiNumericQueryPresenter.class.st
- src/MooseIDE-NewTools/MiPropertyQueryPresenter.class.st
- src/MooseIDE-NewTools/MiQueryBuilderPresenter.class.st
- src/MooseIDE-NewTools/MiQueryCodePresenter.class.st
- src/MooseIDE-NewTools/MiQueryConfigurationPresenter.class.st
- src/MooseIDE-NewTools/MiScopeQueryPresenter.class.st
- src/MooseIDE-NewTools/MiStringQueryPresenter.class.st
- src/MooseIDE-NewTools/MiTypeQueryPresenter.class.st
- src/MooseIDE-NewTools/SpPresenter.extension.st
> show spinner when computing long queries that take a long time

- src/MooseIDE-NewTools-Tests/MiNAryQueryPresenterTest.class.st
- src/MooseIDE-NewTools-Tests/MiNegationQueryPresenterTest.class.st
- src/MooseIDE-NewTools-Tests/MiQueryBuilderPresenterTest.class.st
- src/MooseIDE-NewTools-Tests/MiQueryConfigurationPresenterTest.class.st
- src/MooseIDE-NewTools/MiQueryBuilderPresenter.class.st
> Removed the first query presenter that is created by default.

- src/MooseIDE-NewTools/MiEvaluatorExtension.class.st
- src/MooseIDE-NewTools/MiObjectContextPresenter.class.st
This PR aims to add back a scripting area on demand.
When clicking in the menu bar toogle button, it shows up a scripting area where we can perform complex analysis
> Add Script Area

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- src/MooseIDE-NewTools/MiPlayground.class.st
- src/MooseIDE-NewTools/MiPlaygroundInstalledModelsCommand.class.st
- src/MooseIDE-NewTools/MiPlaygroundModelsPresenter.class.st
- src/MooseIDE-NewTools/MiPlaygroundPage.class.st
- src/MooseIDE-NewTools/MiPlaygroundPagePresenter.class.st
This playground is made with Spec.
It has a toolbar button to add models in the playground code.
> MiPlayground: first version

- src/MooseIDE-Core/MiBusLogsList.class.st
- src/MooseIDE-NewTools/MiInspectorBrowser.class.st
- src/MooseIDE-NewTools/MiObjectContextPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
> Inspector Browser

- .github/workflows/continuous.yml
- .smalltalk.ston
This PR aims to compute our test coverage
> Add coverage

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- src/MooseIDE-Durden/MiDraggableAbstractWidget.class.st
- src/MooseIDE-Durden/MiDraggableRoassalWidget.class.st
- src/MooseIDE-Durden/MiDropIntoBrowser.class.st
- src/MooseIDE-Durden/package.st
Adds two basic widgets for using durden: Abstract general one and Abstract for roassal usage.
For finding durden you may go https://github.com/pharo-contributions/durden
> Adds durden tyler (tiler) to the dependencies.

- src/MooseIDE-QueriesBrowser/FQAbstractQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQBooleanQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQComplementQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQIntersectionQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQNavigationQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQNumericQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQResultSizeQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQScopeQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQStringQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQSubtractionQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQTypeQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQUnionQuery.extension.st
> Moved isAvailableForQueriesSize: an extension method

- src/MooseIDE-QueriesBrowser-Tests/MiQueryListItemPresenter.extension.st
- src/MooseIDE-QueriesBrowser/MiNAryQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiResultTreePresenter.class.st
> improve the receiving entities from the bus mechanism

- src/MooseIDE-QueriesBrowser/MiBooleanQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNAryQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNavigationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNegationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNoPossibleQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNumericQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiPropertyQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryCodePresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryConfiguratorPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiResultSizeQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiScopeQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiStringQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiTypeQueryPresenter.class.st
> remove the update calls 

- src/MooseIDE-NewTools/MiNavigationBrowser.class.st
Fixes #299 
Pair programming with Soufyane
> filtered empty entities from the navigation tab

- src/MooseIDE-QueriesBrowser-Tests/MiSaveQueriesCommandTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/SaveQueriesFixture.class.st
- src/MooseIDE-QueriesBrowser/FQAbstractQuery.extension.st
- src/MooseIDE-QueriesBrowser/FQComplementQuery.extension.st
- src/MooseIDE-QueriesBrowser/MiSaveQueriesCommand.class.st
- src/MooseIDE-QueriesBrowser/TreeQueryHolder.class.st
> Ordering queries when saving

- src/MooseIDE-Core/MiAbstractBrowser.class.st
> Deleted actionsCommandGroupFor: for abstract browser

- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Core/MiBrowserPresenter.class.st
- src/MooseIDE-Core/MiBusPresenter.class.st
- src/MooseIDE-Core/MiOverviewBrowser.class.st
> 332 why do we need mi applicationupdate overview browsers 

- src/MooseIDE-Tests/MiHierarchicalVisualizationBrowserTest.class.st
- src/MooseIDE-Tests/MiHierarchicalVisualizationTest.class.st
- src/MooseIDE-Tests/MiVisualizationThemeTest.class.st
- src/MooseIDE-Visualization/MiHierarchicalVisualization.class.st
- src/MooseIDE-Visualization/MiNodeStyler.class.st
- src/MooseIDE-Visualization/MiVisualizationTheme.class.st
HierarchicalVisualization displays icons for some entities
> Moose icon

- src/MooseIDE-QueriesBrowser/MiRelationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiResultSizeQueryPresenter.class.st
> Added delayer instance variable in MiResultSizeQuery because it was missing

- src/MooseIDE-QueriesBrowser-Tests/MiPropertyQueryPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiScopeQueriesPresenterTest.class.st
- src/MooseIDE-QueriesBrowser/MiNavigationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNegationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiPropertyQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiRelationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiScopeQueryPresenter.class.st
> Start without selection on droplists in QueriesBrowser.

- src/MooseIDE-NewTools/FamixTSourceEntity.extension.st
- src/MooseIDE-NewTools/MiSourceExtension.class.st
> add mi source extension

- src/MooseIDE-Meta/MiImportCommand.class.st
- src/MooseIDE-Meta/MiImportFromFileCommand.class.st
- src/MooseIDE-Meta/MiImportFromJSONCommand.class.st
- src/MooseIDE-Meta/MiImportFromMSECommand.class.st
- src/MooseIDE-Meta/MiImportFromSTCommand.class.st
- src/MooseIDE-Meta/MiImportModelDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromFileDialogTest.class.st
- src/MooseIDE-Meta/MiImportModelFromMSEDialog.class.st
Replaced MSE + JSON --> File
New icons.
Renamed commands
> New import from file dialog.

- src/MooseIDE-Meta/FAMIXModel.extension.st
- src/MooseIDE-Meta/FamixJavaModel.extension.st
- src/MooseIDE-Meta/FamixRepTestModel.extension.st
- src/MooseIDE-Meta/FamixStModel.extension.st
- src/MooseIDE-Meta/FamixTagTestModel.extension.st
- src/MooseIDE-Meta/FamixTest1Model.extension.st
- src/MooseIDE-Meta/FamixTest2Model.extension.st
- src/MooseIDE-Meta/FamixTest3Model.extension.st
- src/MooseIDE-Meta/FamixTest4Model.extension.st
- src/MooseIDE-Meta/FamixTest5Model.extension.st
- src/MooseIDE-Meta/FamixTestComposed1Model.extension.st
- src/MooseIDE-Meta/FamixTestComposed2Model.extension.st
- src/MooseIDE-Meta/FamixTestComposed3Model.extension.st
- src/MooseIDE-Meta/FamixTestComposedComposedModel.extension.st
- src/MooseIDE-Meta/FamixTestComposedModel.extension.st
- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromMSEDialog.class.st
- src/MooseIDE-Meta/MooseModel.extension.st
FamixJavaModel, FamixStModel, FAMIXModel
> Show only models that can be loaded from file.

- src/MooseIDE-CoUsageMap-Browser/MiCoUsageBrowser.class.st
- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Core/MiListSelector.class.st
- src/MooseIDE-Core/MiOverviewBrowser.class.st
- src/MooseIDE-Meta/MiImportModelDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromSmalltalkDialog.class.st
- src/MooseIDE-QueriesBrowser/LoadQueriesPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowserToolbar.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
- src/MooseIDE-QueriesBrowser/NoPossibleQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/QueryCodePresenter.class.st
- src/MooseIDE-QueriesBrowser/QueryCompilerPresenter.class.st
GTK not working right now, but trying to make it possible one day ...
> preparing for Gtk

- src/MooseIDE-CoUsageMap-Browser/MiCoUsageBrowser.class.st
- src/MooseIDE-CoUsageMap-Browser/MiCoUsageMapVisualization.class.st
- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiSettingsCommand.class.st
- src/MooseIDE-Core/MiWindowPresenter.class.st
- src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
> Added infrastructure for settings + started a concrete cas with MiCoUsageBrowser

- src/MooseIDE-CoUsageMap/MiCoFromSettingsMethodAttributeTester.class.st
- src/MooseIDE-CoUsageMap/MiCoMethod.class.st
- src/MooseIDE-CoUsageMap/MiCoTagBuilder.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBuilder.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapSettings.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapSettingsPresenter.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapVisualization.class.st
This pull request addresses these issues:
- https://github.com/moosetechnology/MooseIDE/issues/486
- https://github.com/moosetechnology/MooseIDE/issues/483
> Co usage map update

- src/MooseIDE-CoUsageMap/MiCoFromSettingsMethodAttributeTester.class.st
- src/MooseIDE-CoUsageMap/MiCoMethodAttributeCounter.class.st
- src/MooseIDE-CoUsageMap/MiCoPharoMethodAttributeCounter.class.st
- src/MooseIDE-CoUsageMap/MiCoRangeSettingDeclaration.class.st
- src/MooseIDE-CoUsageMap/MiCoSlider.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBuilder.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapSettings.class.st
this pull request adresses this issue
-https://github.com/moosetechnology/MooseIDE/issues/486
> CousageMap update 

- src/MooseIDE-CoUsageMap/MiCoUsageMapBrowser.class.st
> Added keyboard shortcut to Class comment

- src/MooseIDE-Dependency/HAbstractMenuItem.extension.st
- src/MooseIDE-Dependency/MiHierarchicalMapBuilder.class.st
- src/MooseIDE-Dependency/MiInspectorMenuItem.class.st
Inspect raw model in hierarchical visualization with the moose inspector.
> Fixes #480

- src/MooseIDE-QueriesBrowser/FQAbstractQuery.extension.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesListPresenter.class.st
> Share child queries from queries browser.

- src/MooseIDE-Core/MiWindowPresenter.class.st
> Show settings button in browsers only if it has settings.

- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Core/MiBusesPopup.class.st
- src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
- src/MooseIDE-Tests/MiBusTest.class.st
> Make the last created bus default for opened browser.

- src/MooseIDE-Tagging/MiSmallColorPalette.class.st
> Order list of palettes and list of hues in color picker.

- src/MooseIDE-Dependency/FamixTag.extension.st
- src/MooseIDE-Dependency/MiDMBrowser.class.st
- src/MooseIDE-Dependency/MiDynamicTagSelectionForm.class.st
- src/MooseIDE-QueriesBrowser/MiQueryConfiguratorPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiQueryListItemPresenter.class.st
- src/MooseIDE-Tagging/MiTagBrowserModel.class.st
- src/MooseIDE-Tagging/MiTagManagementPage.class.st
Fix #466
Fix #468
Fix #516
Fix #496
Fix #462
> Corrects some issues

- src/MooseIDE-NewTools-Tests/MiInspectorBrowserTest.class.st
- src/MooseIDE-NewTools/MiInspector.class.st
- src/MooseIDE-NewTools/MiInspectorBrowser.class.st
- src/MooseIDE-NewTools/MiObjectInspectorPresenter.class.st
- src/MooseIDE-Tests/MiAbstractBrowser.extension.st
> updating toolbar of MiInspector when creating/adding a panel/refreshing

- src/MooseIDE-QueriesBrowser/MiScopeQueryPresenter.class.st
> Changed DropList >> #display: from a symbol to a real block

- src/MooseIDE-CoUsageMap/MiCoUsageMapBrowser.class.st
- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiBusLogBrowser.class.st
- src/MooseIDE-Core/MiLogsBrowser.class.st
- src/MooseIDE-Core/MiOverviewBrowser.class.st
- src/MooseIDE-Dependency/MiAbstractDependencyBrowser.class.st
- src/MooseIDE-Dependency/MiDMBrowser.class.st
- src/MooseIDE-Dependency/MiDependencyBrowser.class.st
- src/MooseIDE-Dependency/MiHierarchicalMapBrowser.class.st
- src/MooseIDE-Dependency/MiTreeBrowser.class.st
- src/MooseIDE-Dependency/MiTreeMapVisualisationBrowser.class.st
- src/MooseIDE-Dependency/MiTreeVisualisationBrowser.class.st
- src/MooseIDE-Duplication/MiDuplicationBrowser.class.st
- src/MooseIDE-Durden/MiDraggableDefaultBrowser.class.st
- src/MooseIDE-Durden/MiDropIntoBrowser.class.st
- src/MooseIDE-Export/MiExportBrowser.class.st
- src/MooseIDE-Famix/MiAbstractFamixBrowser.class.st
- src/MooseIDE-Famix/MiFilesBrowser.class.st
- src/MooseIDE-Famix/MiSourceTextBrowser.class.st
- src/MooseIDE-Famix/MiUMLBrowser.class.st
- src/MooseIDE-Meta/MiFameBrowser.class.st
- src/MooseIDE-Meta/MiMetaBrowser.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-Meta/MiMooseModelBrowser.class.st
- src/MooseIDE-Meta/MiPropertyBrowser.class.st
- src/MooseIDE-NewTools/MiInspectorBrowser.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
- src/MooseIDE-Tagging/MiTagBrowser.class.st
- src/MooseIDE-Visualization/MiHierarchicalVisualizationBrowser.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBrowser.class.st
> 561 moose ide overview tool is broken

- src/MooseIDE-Tagging/MiTagEditionForm.class.st
> Correct check when editing tags in tag browser.

- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
> Build browser for DSM Visualization.

- src/MooseIDE-QueriesBrowser/MiNavigationQueryPresenter.class.st
> correct call to #display: for navigation query

- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
> 616 enhance mi dsm

- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMBrowserModel.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
> 621 create a model for dsm browser

- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMBrowserModel.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
- src/MooseIDE-Dependency/MiRSDSM.class.st
> 618 enhance mi dsm browser

- src/MooseIDE-CoUsageMap-Tests/MiCoUsageMapBrowserTest.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBrowser.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapVisualization.class.st
- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiAbstractModel.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
- src/MooseIDE-Dependency/MiDistributionMapModel.class.st
- src/MooseIDE-Duplication/MiDuplicationBrowserModel.class.st
- src/MooseIDE-Meta/MiModelRootBrowserModel.class.st
- src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
Added test for settings + added MiAbstractModel as super class of several Models
> Put more model under MiAbstractModel + added test for settings

- src/MooseIDE-Duplication/MiDuplicationBrowserModel.class.st
> corrected how setting values are retrieved

- src/MooseIDE-ButterflyMap/MiButterflyMapBrowser.class.st
- src/MooseIDE-CoUsageMap-Tests/MiCoUsageMapBrowserTest.class.st
- src/MooseIDE-Core/MiAbstractModel.class.st
- src/MooseIDE-Core/MiBusesPopup.class.st
- src/MooseIDE-Core/MiSettingsPresenter.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBrowser.class.st
- src/MooseIDE-Dependency/MiDMBrowser.class.st
- src/MooseIDE-Duplication/MiDuplicationBrowser.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
- src/MooseIDE-Tests/MiArchitecturalMapBrowserTest.class.st
- src/MooseIDE-Tests/MiDMBrowserTest.class.st
> created test for OK/Cancel/REset buttons 

- src/Famix-CriticBrowser-Entities/FamixCBCondition.class.st
- src/Famix-CriticBrowser-Entities/FamixCBCondition.extension.st
- src/Famix-CriticBrowser-Entities/FamixCBModel.class.st
- src/Famix-CriticBrowser-Entities/FamixCBViolation.class.st
- src/Famix-CriticBrowser-Entities/MooseObject.extension.st
- src/Famix-CriticBrowser-Generator/FamixCriticBrowserGenerator.class.st
FamlixCritics should be able to apply critics on every MooseObject entities
I have updated the metamodel accordingly
> FamixCritic should be linked to moose core

- src/Famix-CriticBrowser-Entities/FamixCBContext.class.st
- src/Famix-CriticBrowser-Entities/FamixCBRootContext.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowser.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowserModel.class.st
This should fix #691 
I replace the location of the _sorts_ to put them only in the UI part
> Improve sort location in the code to link it only with the UI

- src/Famix-CriticBrowser-Entities/FamixCBCondition.class.st
- src/Famix-CriticBrowser-Entities/FamixCBContext.class.st
- src/Famix-CriticBrowser-Entities/FamixCBRootContext.class.st
- src/Famix-CriticBrowser-Entities/FamixCBTRuleComponent.trait.st
- src/Famix-CriticBrowser-Generator/FamixCriticBrowserGenerator.class.st
- src/Famix-CriticBrowser-Tests/FamixCBContextTest.class.st
- src/MooseIDE-CriticBrowser-Tests/AbstractSeverityTest.class.st
- src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserFQQueryTest.class.st
- src/MooseIDE-CriticBrowser/AbstractSeverity.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowser.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowserFQQuery.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowserRulesMakerPresenter.class.st
- src/MooseIDE-CriticBrowser/SeverityError.class.st
- src/MooseIDE-CriticBrowser/SeverityHint.class.st
- src/MooseIDE-CriticBrowser/SeverityInformation.class.st
- src/MooseIDE-CriticBrowser/SeverityWarning.class.st
adding severity level to conditions
> Moose critics severities

- src/MooseIDE-Core/MiDeleteModelCommand.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-Meta/MiModelRootBrowserModel.class.st
> Fix models browser refresh button

- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiBusLogBrowser.class.st
> Correct logger title

- src/MooseIDE-Core/MiDroplistSettingItem.class.st
- src/MooseIDE-Tests/MiSystemComplexityBrowserTest.class.st
- src/MooseIDE-Visualization/MiSystemComplexity.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBrowser.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBuilder.class.st
- src/MooseIDE-Visualization/MiSystemComplexityModel.class.st
> System complexity refactor

- src/MooseIDE-Visualization/MiSystemComplexityBrowser.class.st
- src/MooseIDE-Visualization/MiSystemComplexityModel.class.st
System complexity browser now accept all kinds of moose groups. It filters received moose group, selecting only classes.
> Resolve #704

- src/MooseIDE-ButterflyMap/MiButterflyMapBrowser.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBrowser.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBrowser.class.st
- src/MooseIDE-Dependency/MiDMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDependencyBrowser.class.st
- src/MooseIDE-Dependency/MiTreeMapVisualisationBrowser.class.st
- src/MooseIDE-Dependency/MiTreeVisualisationBrowser.class.st
- src/MooseIDE-Famix/MiUMLBrowser.class.st
- src/MooseIDE-Visualization/MiHierarchicalVisualizationBrowser.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBrowser.class.st
Fix #740 
Consider to refactor controls comment in common super class.
Controls only apply to browser using Roassal which is not currently distinguishable.
> Add controls to help popup in all browser using Roassal.

- src/MooseIDE-Core/Collection.extension.st
- src/MooseIDE-Core/MooseAbstractGroup.extension.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
> Create new method #miPropagate and add test

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueriesBrowserTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueriesListPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueryConfiguratorPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueryListItemPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiTaggedEntityQueryPresenter.extension.st
- src/MooseIDE-QueriesBrowser-Tests/MiTaggedEntityQueryPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/SaveQueriesFixture.class.st
- src/MooseIDE-QueriesBrowser/FQTaggedEntityQuery.extension.st
- src/MooseIDE-QueriesBrowser/MiTaggedEntityQueryPresenter.class.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
- src/MooseIDE-Tests/MiTagBrowserTest.class.st
> 665 queries browser we must have a way to select entities by tag

- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Core/MiBus.class.st
- src/MooseIDE-Core/MiOverviewBrowser.class.st
- src/MooseIDE-Core/MiTestApplication.class.st
- src/MooseIDE-Meta/MiImportCommand.class.st
- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiNAryQueryPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiNegationQueryPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueriesListPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueryConfiguratorPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiQueryListItemPresenterTest.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiResultSizeQueryPresenterTest.class.st
- src/MooseIDE-Tagging-Tests/MiTagPresenterTest.class.st
- src/MooseIDE-Tests/MiAbstractApplicationTest.class.st
- src/MooseIDE-Tests/MiAbstractBrowserTest.class.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
- src/MooseIDE-Tests/MiBrokerageTest.class.st
- src/MooseIDE-Tests/MiBusTest.class.st
implemented Clotilde suggestion:
> that could be nice, you drop a file in the world, it opens the same window as "Import from file" but already filled
> Drop files again

- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMenuItem.class.st
- src/MooseIDE-Dependency/MiArchitecturalMenuItemStrategy.class.st
> Using the menu item builder of HierarchicalVisualizations in architectural map.

- src/Famix-CriticBrowser-Entities/FamixCBModel.class.st
trying to integrate changes in Famix for its issue 437
but this requires to commit this change here too
> changes following #437 of Famix

- src/MooseIDE-Visualization/MiSystemComplexityBuilder.class.st
> 786 system complexity we should review the normalisation of metrics

- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-Meta/MiModelRootBrowserModel.class.st
> fix for 794

- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
> 798 filter out megamorphic methods in architectural map

- src/MooseIDE-Core/MiFollowCommand.class.st
- src/MooseIDE-Core/MiFreezeCommand.class.st
- src/MooseIDE-Core/MiHighlightCommand.class.st
added descriptions for MiReceivingModeCommands 
(the one for propagation has already been described)
> added descriptions for MiReceivingModeCommands

- src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserTest.class.st
- src/MooseIDE-CriticBrowser/FamixCBCondition.extension.st
- src/MooseIDE-CriticBrowser/FamixCBContext.extension.st
- src/MooseIDE-CriticBrowser/FamixCBEntity.extension.st
- src/MooseIDE-CriticBrowser/MiAbstractCriticBrowserCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBAddConditionCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBAddContextCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBDeleteRuleCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBEditRuleCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBMoveToContextCommand.class.st
- src/MooseIDE-CriticBrowser/MiCBRunConditionCommand.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowser.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowserModel.class.st
+ test
+ MiCriticBrowser menu: use commands
> MiCriticBrowser: allow to move a rule component to a different context

- src/MooseIDE-Meta/MiMetaBrowserModel.class.st
> Fixing issue #817

- src/MooseIDE-ButterflyMap/MiButterflyMapModel.class.st
- src/MooseIDE-Dependency/MiTreeVisualizationModel.class.st
- src/MooseIDE-Meta/MiModelRootBrowser.class.st
- src/MooseIDE-Meta/MiModelRootBrowserModel.class.st
- src/MooseIDE-Tests/MiModelRootBrowserTest.class.st
> Work on standardizing MiAbstractModel subclasses

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- src/MooseIDE-ButterflyMap/MiButterflyMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiDistributionMapBuilder.class.st
- src/MooseIDE-Dependency/MiDistributionMapModel.class.st
- src/MooseIDE-Dependency/MiHArchitecturalMapStyle.class.st
- src/MooseIDE-Dependency/MiHDMStyle.class.st
- src/MooseIDE-Visualization/MiHSystemComplexityStyle.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBuilder.class.st
Several visualizations using HierarchicalVisualizations are adapted in order to fit the new usage of HierachicalVisualizaitons.
> Visualizations refactorings

- .smalltalk.ston
- src/MooseIDE-NewTools-Tests/MiInspector.extension.st
- src/MooseIDE-NewTools-Tests/MiModelNavigationBrowser.extension.st
- src/MooseIDE-NewTools-Tests/MiModelNavigationBrowserTest.class.st
- src/MooseIDE-NewTools/MiAbstractGroupNavigationBrowser.class.st
- src/MooseIDE-NewTools/MiModelNavigationBrowser.class.st
- src/MooseIDE-NewTools/MiNavigationBrowser.class.st
Fix selection in model navigation pane
> Fix inspector

- src/Famix-CriticBrowser-Entities/FamixCBCondition.class.st
- src/Famix-CriticBrowser-Entities/FamixCBContext.class.st
- src/Famix-CriticBrowser-Entities/FamixCBRootContext.class.st
- src/Famix-CriticBrowser-Tests/FamixCBContextTest.class.st
- src/Famix-CriticBrowser-Tests/FamixCBRootContextTest.class.st
- src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserTest.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowser.class.st
- src/MooseIDE-CriticBrowser/MiCriticBrowserModel.class.st
reproducing old PR 746 that was never integrated
> Fix fix 700

- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMBrowserModel.class.st
- src/MooseIDE-Tests/MiDSMBrowserTest.class.st
> 874 error in dsm when entities propagated are tags

- src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserModelTest.class.st
- src/MooseIDE-CriticBrowser-Tests/MiCriticBrowserTest.class.st
- src/MooseIDE-Dependency/TEntityMetaLevelDependency.extension.st
- src/MooseIDE-Export/MiExportModel.class.st
- src/MooseIDE-QueriesBrowser-Tests/MiSaveQueriesCommandTest.class.st
- src/MooseIDE-Tests/MiButtonSelectableListSettingItemTest.class.st
> removed all invocations of #asOrderedCollection that were called on objects

- src/MooseIDE-ButterflyMap/MiButterflyMapModel.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBrowser.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
> Fix #858: Add configurable timeout to Architectural Map

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
> Roassal stable versions

- src/MooseIDE-QueriesBrowser/QueryResultTreePresenter.class.st
> Add a menu to the QueryBrowser result pane.

- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapVirtualEntity.class.st
- src/MooseIDE-Tests/MiArchitecturalMapTest.class.st
new experimental feature: Source directories appear as virtual root nodes in the Architectural map
> Architectural map with directories

- src/MooseIDE-Meta/MiModelsBrowser.class.st
Remove unsued variable blockWhenSelection in MiModelsBrowser
> Tiny cleanup

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- Add submenu for different kinds of layouts
- Add layout submenu per node instead of per canvas
- Lazily compute labels 
With this we gain an additional 20% of perfs in the architectural visualization and probably other visualizations using this hierarchical
> Use v1.0.2 of the Hierarchical visualization

- src/MooseIDE-NewTools/MooseModel.extension.st
Because it uses a method that I am removing because it is now useless
> Remove override of MooseModel>>mooseInterestingEntity

- src/MooseIDE-CoUsageMap/MiCoUsageMapModel.class.st
- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Export/MiNoteBookAbstractCell.class.st
- src/MooseIDE-Export/MiNoteBookCodeCell.class.st
- src/MooseIDE-Export/MiNoteBookTextCell.class.st
- src/MooseIDE-QueriesBrowser/MiNAryQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiNegationQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiResultSizeQueryPresenter.class.st
#when:do: got deprecated in P12
> Remove some deprecated calls in P12

- src/MooseIDE-ButterflyMap/MiButterflyMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapVisualization.class.st
- src/MooseIDE-Dependency/MiDistributionMapBuilder.class.st
- src/MooseIDE-Dependency/MiHArchitecturalMapStyle.class.st
- src/MooseIDE-LayerVisualization/MiLayerVisualizationBuilder.class.st
- src/MooseIDE-Visualization/MiSystemComplexityBuilder.class.st
This is one of the steps to improve the architectural map as we discussed in the last moose meeting. 
It focuses on the display of the tags in the labels of the nodes.
I also did some cleaning going with the Hierarchical Visualization project
> Architectural: Improve the displaying of tags in nodes labels

- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiHDistributionMapStyle.class.st
Follow changes from HierarchicalVisu
> Clean the usage of border radius

- src/MooseIDE-Dependency/MiArchitecturalMapBrowser.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
Fixes #871
This issue was closed too early
> Fix the display of tags in the setting of the ArchitecturalMap

- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
Display the kind of entities in the tooltip and the tag names (for the children and the tags directly on the entities)
> Architectural: Make tooltip useful

- src/MooseIDE-Core/FamixTag.extension.st
- src/MooseIDE-Core/MooseObject.extension.st
- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
Fix the display of Architectural map tooltips when we have tags
> Fix the display of tooltips for tags

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
This release has some bug fixes
> Update Roassal to v1.06b

- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
Change in fields revealed a bug. This should fix it.
> Fix import wizard.

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
Fixing some compatibility with Pharo < 12
> Update Roassal to v1.06c

- src/MooseIDE-QueriesBrowser-Tests/MiQueriesBrowserTest.class.st
- src/MooseIDE-QueriesBrowser/MiQueriesBrowser.class.st
- src/MooseIDE-QueriesBrowser/QueryCodePresenter.class.st
Following improvements in Famix-Queries, allow users to execute an entire sequence of queries.
Adapt Query code panel accordingly.
Fix #1010
> Query code improvement

- src/MooseIDE-Core/MooseObject.extension.st
- src/MooseIDE-Core/Object.extension.st
Those methods got moved to Famix last week and they produce a dirty moose image
> Remove #isMooseObject

- src/MooseIDE-Meta/MiImportModelFromSmalltalkDialog.class.st
Remove unused variable and remove factory that is used to create one entity and that we never change in MooseIDE.
> Clean the St importer dialog

- src/MooseIDE-QueriesBrowser-Tests/MiTypeQueryPresenter.extension.st
- src/MooseIDE-QueriesBrowser-Tests/MiTypeQueryPresenterTest.class.st
- src/MooseIDE-QueriesBrowser/MiTypeQueryPresenter.class.st
- src/MooseIDE-QueriesBrowser/MiTypeSelectionPresenter.class.st
> 1072 query browser should open dialogs instead of tiny tooltips

- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Tagging-Tests/MiTagCreationFormTest.class.st
fix issue #960 
copy query/tag before consuming them
> fix issue #960

- src/MooseIDE-Meta/MiModelsBrowser.class.st
- src/MooseIDE-Meta/MiModelsBrowserModel.class.st
- Do not display models randomly but display them by installation order
- Add info about the language and number of entities
> Improve models browser

- src/MooseIDE-Core/MiAbstractBrowser.class.st
- src/MooseIDE-Core/MiApplication.class.st
- src/MooseIDE-Meta/MiModelsBrowser.class.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
Behavior set in the Application.
> Only one Models browser opened at a time.

- src/MooseIDE-Core/MiOverviewBrowser.class.st
It does not work and is not used.
It tries something like a workspace but it probably is not the place.
Fix #611
> Remove "Open in page" button.

- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromSmalltalkDialog.class.st
> Fix #1147. Allow to navigate between screens

- src/MooseIDE-NewTools/MiModelNavigationBrowser.class.st
- src/MooseIDE-NewTools/MiNavigationBrowser.class.st
When inspecting a model we have the navigation tab. I updated the code to show only elements that are not empty and I also added a column to know the number of entities
> Improve UX of navigation tab

- src/MooseIDE-NewTools/MiMetaModelNavigationBrowser.class.st
fix #1141 
- fix the comment here https://github.com/moosetechnology/MooseIDE/issues/1141#issuecomment-2363099133
> restore all model entries

- src/MooseIDE-Duplication/MiDuplicationBrowser.class.st
- src/MooseIDE-Duplication/MiDuplicationBrowserModel.class.st
> 1168 dulication browser should show members of a clone in the left most list

- src/MooseIDE-Core/FamixTAnnotationType.extension.st
- src/MooseIDE-Core/FamixTAttribute.extension.st
- src/MooseIDE-Core/FamixTFunction.extension.st
- src/MooseIDE-Core/FamixTStructuralEntity.extension.st
> Set default mooseIcons for some generic entities

- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
> ArchitecturalMap now has all possible links shown by default

- src/MooseIDE-Core/MooseLoadMoosePyMenuCommand.class.st
> Adding MoosePy to menu library in Moose

- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st
- src/MooseIDE-Dependency/MiRSDSMShape.class.st
- src/MooseIDE-Dependency/MiRSDependencyStructuralMatrix.class.st
- src/MooseIDE-Dependency/MooseEntity.extension.st
Small improvements to DSM
also fix #1203
> DSM interactions

- src/MooseIDE-Core/MiAccumulatorBrowser.class.st
- src/MooseIDE-Core/MiAccumulatorBrowserModel.class.st
- src/MooseIDE-Duplication/MiDuplicationBrowserModel.class.st
- src/MooseIDE-Export/MiExportBrowser.class.st
- src/MooseIDE-Meta/MiMetaBrowser.class.st
- src/MooseIDE-Tests/MiAccumulatorBrowserTest.class.st
a new tool to create manually a list of entities to propagate
> Accumulator

- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowser.class.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixVisualization.class.st
- src/MooseIDE-Dependency/MiRSDSMShape.class.st
- src/MooseIDE-Dependency/MiRSDependencyStructuralMatrix.class.st
integrating detailedDSM (drill down in DSM)
> Detailed dsm

- src/MooseIDE-Export/MiExportBrowser.class.st
- src/MooseIDE-Export/MiExportModel.class.st
Instead of #1196 as discussed with @ISayarLu
> Exporter column duplication alternative

- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowser.class.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixVisualization.class.st
- src/MooseIDE-Dependency/MiRSDependencyStructuralMatrix.class.st
- src/MooseIDE-Tests/MiDependencyStructuralMatrixBrowserTest.class.st
> Zoom-in stops when reaching methods or attributes or empty dependencies.

- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowser.class.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st
- src/MooseIDE-Meta/MiModelsBrowserModel.class.st
- src/MooseIDE-Tests/MiDependencyStructuralMatrixBrowserTest.class.st
Added a setting in DSM to show or not weights on the diagonal
Added tests
> Setting diagonal

- src/MooseIDE-Dependency/FamixTMethod.extension.st
- src/MooseIDE-Dependency/FamixTTypedEntity.extension.st
- src/MooseIDE-Dependency/MiDependencyStructuralMatrixBrowserModel.class.st
- Concretizations are not children of entities where they appear (they are associations)
- dependencies to concretization should be counted as dependencies to their generic entity All this should disapear with the new modelization of generics
> Temporarily solved some problems w/ generics in DSM

- src/MooseIDE-CoUsageMap/MiCoUsageMapAbstractSettingsPresenter.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBrowser.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBuilder.class.st
working on #1248 
Cleaned a bit code
Implemented a missing method
> 1248 co usage map needs a cleaning

- src/MooseIDE-Meta/MiImportModelDialog.class.st
- src/MooseIDE-Meta/MiModelsBrowserModel.class.st
- src/MooseIDE-Tests/MiModelsBrowserTest.class.st
> 1257 setting import without cache in models browser import not working

- src/MooseIDE-CoUsageMap/MiCoPharoMethodAttributeCounter.class.st
- src/MooseIDE-CoUsageMap/MiCoTagLegendBuilder.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapModel.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapVisualization.class.st
- src/MooseIDE-Core/MiAbstractModel.class.st
removed the error, but coUsageMap still does not handle correctly modifying TagAssociations from outside
> 1259 MiCoUsageMapBuilder DNU containerBoxes

- src/MooseIDE-Dependency/FamixTClass.extension.st
- src/MooseIDE-Dependency/FamixTFunction.extension.st
- src/MooseIDE-Dependency/FamixTMethod.extension.st
- src/MooseIDE-Dependency/FamixTPackage.extension.st
- src/MooseIDE-Dependency/FamixTStructuralEntity.extension.st
- src/MooseIDE-Dependency/FamixTTypedEntity.extension.st
- src/MooseIDE-Dependency/MiDSMBrowser.class.st
- src/MooseIDE-Dependency/MiDSMBrowserModel.class.st
- src/MooseIDE-Dependency/MiDSMDependencyGraph.class.st
- src/MooseIDE-Dependency/MiDSMDependencyManager.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
- src/MooseIDE-Dependency/MiRSDSM.class.st
- src/MooseIDE-Dependency/MooseEntity.extension.st
- src/MooseIDE-Dependency/TEntityMetaLevelDependency.extension.st
- src/MooseIDE-Tests/MiDSMBrowserTest.class.st
- src/MooseIDE-Tests/MiDependencyStructuralMatrixBrowserTest.class.st
Implemented the stuff, but needs to be checked thoroughly because now numbers are very different from what they were before...
fix #1270
> 1270 in dsm allow to merge sub package dependencies into their parent package dependencies

- src/MooseIDE-CoUsageMap/MiCoUsageMapBlockSettingsPresenter.class.st
> fixing coUsageMap issue 1284

- src/MooseIDE-Famix/MiExternalEditorOpenner.class.st
> correcting MiSourceCodeIssue 1285

- src/MooseIDE-CoUsageMap-Tests/MiCoUsageMapBrowserTest.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapBlockSettingsPresenter.class.st
- src/MooseIDE-CoUsageMap/MiCoUsageMapSettings.class.st
> Closing on "Apply" button + added "close button" + tests

- src/BaselineOfMooseIDE/BaselineOfMooseIDE.class.st
- src/MooseIDE-Core-Reporter/MiModelReporter.class.st
- src/MooseIDE-Core-Reporter/MiModelReporterModel.class.st
Added preview tab to the ModelReporter
> ModelReporter

- src/MooseIDE-Visualization/MiAbstractVisualization.class.st
> Fix canvas interactions when settings are updated.

- src/MooseIDE-ButterflyMap/MiButterflyMapVisualization.class.st
> Add canva controllers to butterfly map

- src/MooseIDE-Export/MiNotebookBrowser.class.st
> Replace association by workspace variable for the notebook bindings.

- src/MooseIDE-NewTools/MiPlaygroundBrowser.class.st
> Update Tool registry API usage to be compatible with P13

- src/MooseIDE-Core/MiBusLogBrowser.class.st
- src/MooseIDE-Core/MiLogger.class.st
- src/MooseIDE-Core/MiLogsBrowser.class.st
- src/MooseIDE-Tests/MiApplicationTest.class.st
- src/MooseIDE-Tests/MiBusLogBrowserTest.class.st
- src/MooseIDE-Tests/MiLoggerTest.class.st
- src/MooseIDE-Tests/MiLogsBrowserTest.class.st
trying the same PR as #1316  with my user...
> 1311 allow to select several log entries in the logger

- src/MooseIDE-Dependency/MiDSMBrowserModel.class.st
- src/MooseIDE-Dependency/MiDSMVisualization.class.st
- src/MooseIDE-Dependency/MiRSDSM.class.st
- src/MooseIDE-Tests/MiDSMBrowserTest.class.st
> 1319 dsm  allow consulting the dependencies associated to a cell

- src/MooseIDE-Tagging-Tests/MiTagBrowserTest.class.st
- src/MooseIDE-Tagging/MiTagManagementPage.class.st
> 1332 tag browser unselect a tag when receiving entities

- src/MooseIDE-Core/MiModelExportCommand.class.st
I added model name as default filename
> Fix: ModelBrowser export default filename 557

- src/MooseIDE-Meta/MiImportModelDialog.class.st
If clicked twice, display a warning dialog .
> Fix : Model importer allows to click twice on OK button. 

- src/Famix-CriticBrowser-Entities/FamixCBCondition.class.st
- src/Famix-CriticBrowser-Entities/FamixCBContext.class.st
- src/Famix-CriticBrowser-Entities/FamixCBRootContext.class.st
- src/Famix-CriticBrowser-ManualEntities/FamixCBRunner.class.st
- src/Famix-CriticBrowser-Tests/FamixCBRootContextTest.class.st
- src/Famix-CriticBrowser-Tests/FamixCBRunnerTest.class.st
- src/Famix-CriticBrowser-Tests/FamixCBTestRule.class.st
Needed by BL to avoid using MiCriticBrowser.
This is a fisrt step while re-engineering the critics.
> Add a runner for Critics + tests.

- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
- src/MooseIDE-Tests/MiModelsBrowserTest.class.st
> Add MIiImporttModelFromFileDialog>>windowTitle method

- src/MooseIDE-Meta/MiImportModelDialog.class.st
Fix #1334 but cleaner. In my opinion ofc.
> Fix : Model importer allows to click twice on OK button #1306

- src/MooseIDE-NewTools/MiMetaNavigationBrowser.class.st
Navigation tab properties button
> Fix #1365.

- src/MooseIDE-Meta/MiImportModelDialog.class.st
- src/MooseIDE-Meta/MiImportModelFromFileDialog.class.st
This fixes the title of the Smalltalk and JavaFolders importer dialog
> Fix some window titles

- src/MooseIDE-QueriesBrowser/QueryCompilerPresenter.class.st
> adding a close button to the popover presenter of manual queries

- src/MooseIDE-LayerVisualization/MiLayerVisualizationBrowser.class.st
> remove LayerVisualization from the Moose menu

- src/MooseIDE-Core/MiAbstractRadioButtonSettingPresenter.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapBuilder.class.st
- src/MooseIDE-Dependency/MiArchitecturalMapModel.class.st
- src/MooseIDE-Dependency/MiForceBasedLayout.class.st
- src/MooseIDE-Dependency/MiLayoutSettingPresenter.class.st
> 1406 add force based layout to architectural map

- src/MooseIDE-API-Browser/HSelectRelatedMenuItem.class.st
- src/MooseIDE-API-Browser/HUnselectRelatedMenuItem.class.st
- src/MooseIDE-API-Browser/HUpdateTagsMenuItem.class.st
- src/MooseIDE-API-Browser/MiAPIBrowser.class.st
- src/MooseIDE-API-Browser/MiAPIBrowserSettingsConfiguration.class.st
- src/MooseIDE-API-Browser/MiAPIMapBuilder.class.st
- src/MooseIDE-API-Browser/MiAPIMapModel.class.st
- src/MooseIDE-API-Browser/MiAPIVisualization.class.st
- src/MooseIDE-API-Browser/package.st
- src/MooseIDE-Core/MooseLoadAPIBrowserMenuCommand.class.st
Adding a new tool: API browser (initially created for analyzing Corese code)
> Api browser
